#:schema node_modules/wrangler/config-schema.json
name = "smail"
compatibility_date = "2024-09-25"
main = "app/worker.ts"
assets = { directory = "./build/client" }

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "17fe9a713d2343438079e6c30b182502"

[[d1_databases]]
binding = "DB"
database_name = "smail"
database_id = "8da4ae30-4077-4228-9346-84c8b5a4e70b"
preview_database_id = "8da4ae30-4077-4228-9346-84c8b5a4e70b"
migrations_dir = "app/drizzle"
